export {
  CURRICULUM_ID_NAMESPACES,
  CURRICULUM_ID_PATTERN,
  NAMESPACE_ID_PATTERNS,
  isCurriculumIdNamespace,
  isValidCurriculumId,
  parseCurriculumId,
  type CurriculumIdNamespace,
} from "./types/ids.ts";

export type {
  AssetKind,
  AssetReference,
  ComprehensionItem,
  ComprehensionType,
  ContentDifficulty,
  ContentStatus,
  CurriculumAction,
  CurriculumBundle,
  CurriculumBundleMeta,
  CurriculumLevel,
  CurriculumLevelId,
  ExerciseChoice,
  ExerciseDefinition,
  ExerciseDifficulty,
  ExerciseMasteryTarget,
  ExerciseSuccess,
  ExerciseType,
  FrequencyBand,
  InformationalTextDefinition,
  LearningPathDefinition,
  LearningUnitDefinition,
  LetterDefinition,
  LetterFormRef,
  LetterForms,
  LetterFormSlot,
  MasteryEvidence,
  MsaStatus,
  ReadingContentBase,
  ReadingPage,
  SentenceDefinition,
  SkillDefinition,
  SkillDomain,
  SkillModality,
  StoryDefinition,
  SuccessType,
  SyllableDefinition,
  SyllablePattern,
  UnitMasteryCriteria,
  VocabBand,
  VocabSubBand,
  WordDefinition,
} from "./types/models.ts";

export {
  asCurriculumBundle,
  validateCurriculum,
  BAND_A_PRODUCTION_META_ID,
  BAND_A_V1_WORD_COUNT,
  isBandAProductionBundle,
  validateBandAProduction,
  LITERACY_WAVE1_META_ID,
  WAVE1_LETTER_IDS,
  WAVE1_PATH_ID,
  WAVE1_WORD_IDS,
  isLiteracyWave1Bundle,
  validateLiteracyWave1Production,
  validateLiteracyWordsAgainstBandA,
  SHARED_SKILLS_CATALOG_ID,
  catalogSkillsFrom,
  skillIdentityKey,
  validateSkillsAgainstCatalog,
  type ValidationIssue,
  type ValidationResult,
  type ValidationSeverity,
} from "./validation/validateCurriculum.ts";
