export {
  asCurriculumBundle,
  validateCurriculum,
  BAND_A_PRODUCTION_META_ID,
  BAND_A_V1_WORD_COUNT,
  isBandAProductionBundle,
  validateBandAProduction,
  LITERACY_WAVE1_META_ID,
  WAVE1_LETTER_IDS,
  WAVE1_PATH_ID,
  WAVE1_WORD_IDS,
  isLiteracyWave1Bundle,
  validateLiteracyWave1Production,
  validateLiteracyWordsAgainstBandA,
  SHARED_SKILLS_CATALOG_ID,
  catalogSkillsFrom,
  skillIdentityKey,
  validateSkillsAgainstCatalog,
  type ValidationIssue,
  type ValidationResult,
  type ValidationSeverity,
} from "./validateCurriculum.ts";
