/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiacriticsIndexRouteImport } from './routes/diacritics/index'
import { Route as LearnIndexRouteImport } from './routes/learn/index'
import { Route as LettersIndexRouteImport } from './routes/letters/index'
import { Route as LettersIdRouteImport } from './routes/letters/$id'
import { Route as ParentsIndexRouteImport } from './routes/parents/index'
import { Route as SentencesIndexRouteImport } from './routes/sentences/index'
import { Route as StoriesIndexRouteImport } from './routes/stories/index'
import { Route as WordsIndexRouteImport } from './routes/words/index'
import { Route as LearnWaveIdUnitIdRouteImport } from './routes/learn/$waveId.$unitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiacriticsIndexRoute = DiacriticsIndexRouteImport.update({
  id: '/diacritics/',
  path: '/diacritics/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersIndexRoute = LettersIndexRouteImport.update({
  id: '/letters/',
  path: '/letters/',
  getParentRoute: () => rootRouteImport,
} as any)
const LettersIdRoute = LettersIdRouteImport.update({
  id: '/letters/$id',
  path: '/letters/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsIndexRoute = ParentsIndexRouteImport.update({
  id: '/parents/',
  path: '/parents/',
  getParentRoute: () => rootRouteImport,
} as any)
const SentencesIndexRoute = SentencesIndexRouteImport.update({
  id: '/sentences/',
  path: '/sentences/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoriesIndexRoute = StoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const WordsIndexRoute = WordsIndexRouteImport.update({
  id: '/words/',
  path: '/words/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnWaveIdUnitIdRoute = LearnWaveIdUnitIdRouteImport.update({
  id: '/learn/$waveId/$unitId',
  path: '/learn/$waveId/$unitId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/letters/$id': typeof LettersIdRoute
  '/diacritics/': typeof DiacriticsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/letters/': typeof LettersIndexRoute
  '/parents/': typeof ParentsIndexRoute
  '/sentences/': typeof SentencesIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/words/': typeof WordsIndexRoute
  '/learn/$waveId/$unitId': typeof LearnWaveIdUnitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/letters/$id': typeof LettersIdRoute
  '/diacritics': typeof DiacriticsIndexRoute
  '/learn': typeof LearnIndexRoute
  '/letters': typeof LettersIndexRoute
  '/parents': typeof ParentsIndexRoute
  '/sentences': typeof SentencesIndexRoute
  '/stories': typeof StoriesIndexRoute
  '/words': typeof WordsIndexRoute
  '/learn/$waveId/$unitId': typeof LearnWaveIdUnitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/letters/$id': typeof LettersIdRoute
  '/diacritics/': typeof DiacriticsIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/letters/': typeof LettersIndexRoute
  '/parents/': typeof ParentsIndexRoute
  '/sentences/': typeof SentencesIndexRoute
  '/stories/': typeof StoriesIndexRoute
  '/words/': typeof WordsIndexRoute
  '/learn/$waveId/$unitId': typeof LearnWaveIdUnitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/letters/$id'
    | '/diacritics/'
    | '/learn/'
    | '/letters/'
    | '/parents/'
    | '/sentences/'
    | '/stories/'
    | '/words/'
    | '/learn/$waveId/$unitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/letters/$id'
    | '/diacritics'
    | '/learn'
    | '/letters'
    | '/parents'
    | '/sentences'
    | '/stories'
    | '/words'
    | '/learn/$waveId/$unitId'
  id:
    | '__root__'
    | '/'
    | '/letters/$id'
    | '/diacritics/'
    | '/learn/'
    | '/letters/'
    | '/parents/'
    | '/sentences/'
    | '/stories/'
    | '/words/'
    | '/learn/$waveId/$unitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LettersIdRoute: typeof LettersIdRoute
  DiacriticsIndexRoute: typeof DiacriticsIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  LettersIndexRoute: typeof LettersIndexRoute
  ParentsIndexRoute: typeof ParentsIndexRoute
  SentencesIndexRoute: typeof SentencesIndexRoute
  StoriesIndexRoute: typeof StoriesIndexRoute
  WordsIndexRoute: typeof WordsIndexRoute
  LearnWaveIdUnitIdRoute: typeof LearnWaveIdUnitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diacritics/': {
      id: '/diacritics/'
      path: '/diacritics'
      fullPath: '/diacritics/'
      preLoaderRoute: typeof DiacriticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters/': {
      id: '/letters/'
      path: '/letters'
      fullPath: '/letters/'
      preLoaderRoute: typeof LettersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/letters/$id': {
      id: '/letters/$id'
      path: '/letters/$id'
      fullPath: '/letters/$id'
      preLoaderRoute: typeof LettersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents/': {
      id: '/parents/'
      path: '/parents'
      fullPath: '/parents/'
      preLoaderRoute: typeof ParentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentences/': {
      id: '/sentences/'
      path: '/sentences'
      fullPath: '/sentences/'
      preLoaderRoute: typeof SentencesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stories/': {
      id: '/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof StoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/words/': {
      id: '/words/'
      path: '/words'
      fullPath: '/words/'
      preLoaderRoute: typeof WordsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$waveId/$unitId': {
      id: '/learn/$waveId/$unitId'
      path: '/learn/$waveId/$unitId'
      fullPath: '/learn/$waveId/$unitId'
      preLoaderRoute: typeof LearnWaveIdUnitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LettersIdRoute: LettersIdRoute,
  DiacriticsIndexRoute: DiacriticsIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  LettersIndexRoute: LettersIndexRoute,
  ParentsIndexRoute: ParentsIndexRoute,
  SentencesIndexRoute: SentencesIndexRoute,
  StoriesIndexRoute: StoriesIndexRoute,
  WordsIndexRoute: WordsIndexRoute,
  LearnWaveIdUnitIdRoute: LearnWaveIdUnitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
